version: "3.7"

services:
  api:
    build: .

    environment:
      - DATABASE_URL=postgresql://admin:8da7881db3a666409d350f702d25784f@postgres:5432/ofertas_saas

    networks:
      - interna

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api-ofertas.wrtec.com.br`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

networks:
  interna:
    external: true